wget http://jacebook.co.uk/share/html5/images/mushroom.png
wget http://jacebook.co.uk/share/html5/images/mushroom2.png
wget http://jacebook.co.uk/share/html5/images/forest1.jpg
wget http://jacebook.co.uk/share/html5/images/bear_eyesopen.png
wget http://jacebook.co.uk/share/html5/images/bear_eyesclosed.png
wget http://jacebook.co.uk/share/html5/images/flower.png
wget http://jacebook.co.uk/share/html5/images/acorn.png
wget http://jacebook.co.uk/share/html5/images/leaf.png
wget http://jacebook.co.uk/share/html5/images/score.png
wget http://jacebook.co.uk/share/html5/images/owl1.png
wget http://jacebook.co.uk/share/html5/images/owl2.png
wget http://jacebook.co.uk/share/html5/images/comboBonus0.png
wget http://jacebook.co.uk/share/html5/images/comboBonus1.png
wget http://jacebook.co.uk/share/html5/images/comboBonus2.png
wget http://jacebook.co.uk/share/html5/images/lives0.png
wget http://jacebook.co.uk/share/html5/images/lives1.png
wget http://jacebook.co.uk/share/html5/images/lives2.png
wget http://jacebook.co.uk/share/html5/images/lives3.png
wget http://jacebook.co.uk/share/html5/images/lives4.png
wget http://jacebook.co.uk/share/html5/images/lives5.png
wget http://jacebook.co.uk/share/html5/sounds/boing_1.mp3
wget http://jacebook.co.uk/share/html5/sounds/boing_2.mp3
wget http://jacebook.co.uk/share/html5/sounds/boing_3.mp3
wget http://jacebook.co.uk/share/html5/sounds/boing_4.mp3
wget http://jacebook.co.uk/share/html5/sounds/boing_5.mp3
wget http://jacebook.co.uk/share/html5/sounds/crowdgroan.mp3
wget http://jacebook.co.uk/share/html5/sounds/collisionPrize.mp3
wget http://jacebook.co.uk/share/html5/sounds/collisionStarPrize.mp3
wget http://jacebook.co.uk/share/html5/sounds/groan.mp3
wget http://jacebook.co.uk/share/html5/sounds/newLevel.mp3
wget http://jacebook.co.uk/share/html5/sounds/owl.mp3
wget http://jacebook.co.uk/share/html5/sounds/squawk.mp3
wget http://jacebook.co.uk/share/html5/sounds/boing_1.wav
wget http://jacebook.co.uk/share/html5/sounds/boing_2.wav
wget http://jacebook.co.uk/share/html5/sounds/boing_3.wav
wget http://jacebook.co.uk/share/html5/sounds/boing_4.wav
wget http://jacebook.co.uk/share/html5/sounds/boing_5.wav
wget http://jacebook.co.uk/share/html5/sounds/crowdgroan.wav
wget http://jacebook.co.uk/share/html5/sounds/collisionPrize.wav
wget http://jacebook.co.uk/share/html5/sounds/collisionStarPrize.wav
wget http://jacebook.co.uk/share/html5/sounds/groan.wav
wget http://jacebook.co.uk/share/html5/sounds/newLevel.wav
wget http://jacebook.co.uk/share/html5/sounds/owl.wav
wget http://jacebook.co.uk/share/html5/sounds/squawk.wav
wget http://jacebook.co.uk/share/html5/sounds/birds.wav
